services:
  caddy:
    image: caddy
    container_name: polylend-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./src:/wwwroot
    restart: unless-stopped
  web:
    image: polylend-web
    container_name: polylend-web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]
  landing:
    image: polylend-landing
    context: ./landing
    container_name: polylend-landing
    build:
      context: ./landing
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]
